version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/FinalProject

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - run: 
            command: |
                pwd
      - run: 
            command: |
<<<<<<< HEAD
                ls 
      - run: 
            command: |
                cd ..
      - run: 
            command: |
                cd ..
      - run: 
            command: |
                pwd
      - run: 
            command: |
                ls           
=======
                ls
                
>>>>>>> 7c5049ae8cbd2c2434c22c7ae672ebf5a1140136
            

