version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
       
    steps:
      - add_ssh_keys:
            fingerprints:
                - "f0:b0:30:88:67:cb:2c:7b:75:f0:0b:2d:26:a6:4e:b2"
      - checkout
     
      - run: 
            command: |
                cd src/    
      - run: 
            command: |
                ls -l