version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - run: 
            command: |
                cd ..
      - run: 
            command: |
                ls -l      
