version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/home

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - run: 
            command: |
                pwd
      - run: 
            command: |
                cd "../../.."        
      - run: 
            command: |
                pwd      

